version: "3" 
services:
  wp_main:
    container_name: wp_main
    image: webdevops/php-apache:7.4
    volumes:
      - wp_main:/app

  wp_test:
    container_name: wp_test
    image: webdevops/php-nginx:7.4
    volumes:
      - wp_test:/app

  db_main:
    image: mariadb:10.5.9
    container_name: db_main
    volumes:
      - db_main:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  db_test:
    image: mariadb:10.5.9
    container_name: db_test
    volumes:
      - db_test:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  router:
    image: haproxy:2.4-dev
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./ssl:/etc/ssl

volumes:
  wp_main:
  wp_test:
  db_main:
  db_test: